version: "3.8"

networks:
  avanc_network:
    driver: bridge

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx:/etc/nginx/conf.d:ro
      - static_volume:/var/www/static
    networks:
      - avanc_network
    depends_on:
      - service
    ports:
      - 80:80

  service:
    build: avanc-admin
    env_file:
      - .env
    depends_on:
      - database
    volumes:
      - static_volume:/opt/app/static
    networks:
      - avanc_network

  database:
    image: postgres:16

    container_name: postgres_avanc
    restart: on-failure
    env_file:
      - .env

    volumes:
      - postgres_data:/var/lib/postgresql/data

    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - avanc_network

volumes:
  postgres_data:
  static_volume:
