# Generated by Django 4.2.11 on 2024-11-07 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salaryadvancerequest",
            name="status",
            field=models.CharField(
                auto_created=True,
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
                verbose_name="status",
            ),
        ),
    ]
