# Generated by Django 4.2.11 on 2024-12-18 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_employee_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
