# Generated by Django 4.2.11 on 2024-12-18 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0004_alter_employee_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salaryadvancerequest",
            name="status",
            field=models.CharField(
                auto_created=True,
                choices=[
                    ("pendiente", "Pendiente"),
                    ("aprobado", "Aprobado"),
                    ("rechazado", "Rechazado"),
                ],
                default="pendiente",
                max_length=20,
                verbose_name="status",
            ),
        ),
    ]
